version: "3"

volumes:
  traefik-certs:

services:
  getraenkekassengeraete:
    build: .
    environment:
      RUST_LOG: debug
    # the geraete container allows hotplugging of all the devices. unfortunately this is not compatible
    # with the way that docker handles devices
    # for --device the device has to be present (i.e. it wouldn't be possible to start it without nfc AND storno connected)
    # privileged hands over all devices in /dev but ONLY a snapshot of what was there at the time
    # the only solution I found was to use privileged (so we can actually open() the devices) and mounting the host /dev fs
    privileged: true
    volumes:
      - /dev:/dev
      - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
    labels:
      traefik.enable: "true"
      traefik.http.routers.getraenkekassengeraete-http.rule: PathPrefix(`/`)
      traefik.http.routers.getraenkekassengeraete-http.entrypoints: web

  traefik:
    network_mode: host
    image: traefik:v2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certs:/var/traefik_certs
      - ./docker-compose/traefik.toml:/etc/traefik/traefik.toml
