[log]
#level = "DEBUG"

[api]
dashboard = true
insecure = true

[providers]
    [providers.docker]
        exposedByDefault = false
        endpoint = "unix:///var/run/docker.sock"

[entryPoints]
    [entryPoints.web]
        address = ":80"
