name: Deploy Docker

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # https://github.com/tonistiigi/binfmt/issues/122#issuecomment-1359175441
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: linux/arm64, linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to quay Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: kalkspace+github
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}
            quay.io/${{ github.repository }}:latest
